### ISSUE TITLE
TextKBQA also failed on example...

### ISSUE THREAD

**Issue by SeekPoint** [rajarshd/ChainsofReasoning#8]
I paste the issue on this project since the TextKQQA cannot do that

Num questions 1
No pretrained entity & word embeddings available. Learning entity embeddings from scratch
Traceback (most recent call last):
  File "/Users/yike.ke/yike_prj/TextKBQA/code/train.py", line 353, in <module>
    t = Trainer()
  File "/Users/yike.ke/yike_prj/TextKBQA/code/train.py", line 45, in __init__
    separate_key_lstm=separate_key_lstm)
  File "/Users/yike.ke/yike_prj/TextKBQA/code/KBQA.py", line 291, in __init__
    super(TextKBQA, self).__init__(**kwargs)
  File "/Users/yike.ke/yike_prj/TextKBQA/code/KBQA.py", line 67, in __init__
    self.entity_lookup_table_extended = tf.concat(0, [self.entity_lookup_table, self.entity_dummy_mem])
  File "/Library/Python/2.7/site-packages/tensorflow/python/ops/array_ops.py", line 1029, in concat
    dtype=dtypes.int32).get_shape(
  File "/Library/Python/2.7/site-packages/tensorflow/python/framework/ops.py", line 639, in convert_to_tensor
    as_ref=False)
  File "/Library/Python/2.7/site-packages/tensorflow/python/framework/ops.py", line 704, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/Library/Python/2.7/site-packages/tensorflow/python/framework/constant_op.py", line 113, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/Library/Python/2.7/site-packages/tensorflow/python/framework/constant_op.py", line 102, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/Library/Python/2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 370, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/Library/Python/2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 302, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got <tf.Variable 'entity_lookup_table:0' shape=(1817564, 50) dtype=float32_ref> of type 'Variable' instead.

**Comment by SeekPoint** [comment]
wrong path issue
